// export const SET_SHOW_HIDE_COMPANY_WINDOW = 'SET_SHOW_HIDE_COMPANY_WINDOW'

export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const GET_SINGLE_COMPANY = "GET_SINGLE_COMPANY";